### ISSUE TITLE
Unable to add SmartyPants extension via AddSetting

### ISSUE THREAD

**Issue by kentcb** [statiqdev/Statiq.Framework#266] opened 2023-05-06 23:29 UTC
Hi,

The following code:

```fsharp
    Bootstrapper
        .Factory
        .CreateWeb(argv)
        .AddSetting(Statiq.Markdown.MarkdownKeys.MarkdownExtensions, ResizeArray(seq { "Bootstrap"; "CustomContainer"; "SmartyPants" }))
        .RunAsync()
```

fails at runtime with:

```
[ERRO] Content/Process » CacheDocuments » RenderContentProcessTemplates » ExecuteIf » RenderMarkdown » [C:/Users/.../index.md => index.html] Markdown extension SmartyPants does not have a usable constructor
```

Indeed, it does appear as though the extension code is a little bit different in that it takes an optional `Settings` object, but it's unclear to me whether it should just work because it's optional and, if not, how to provide the options via the `AddSetting` extension.

**Comment by daveaglick** [comment] 2023-05-15 19:37
That value syntax for the MarkdownExtensions looks like F#? And if so, is the C# equivalent `new [] { "Bootstrap", "CustomContainer", "SmartyPants" }` to make sure I'm doing the same thing?

**Comment by daveaglick** [comment] 2023-05-15 19:56
I'm able to replicate this, and the problematic code is here:
![image](https://github.com/statiqdev/Statiq.Framework/assets/1020407/e3572d10-4395-4fa7-8cd4-c35da41639bf)

There's probably a few things that need to be done here to improve extension loading. For one, it does try to fill a non-default constructor with default arguments, but maybe that's not working in this case because the SmartyPants extension is expecting a nullable (need to research this part more).

You can already add extension instances today by modifying the Markdown template and `RenderMarkdown` module:
```
await Bootstrapper.Factory
    .CreateWeb(args)
    .ModifyTemplate(
        MediaTypes.Markdown,
        x => ((RenderMarkdown)x)
            .UseExtension<BootstrapExtension>()
            .UseExtension<CustomContainerExtension>()
            .UseExtension(new SmartyPantsExtension(new SmartyPantOptions())))
    .RunAsync();
```

This compiles and runs, but I still don't see the revised characters in the output, so I'll need to look more closely at this approach as well. Stay tuned...

**Comment by daveaglick** [comment] 2023-05-16 18:05
Okay, I take it back about the code block above not working - `.UseExtension(new SmartyPantsExtension(new SmartyPantOptions()))` does appear to work as intended and enable the SmartyPant extension, I just didn't know what I was looking for.

Without:
![image](https://github.com/statiqdev/Statiq.Framework/assets/1020407/92c96cc2-ab07-42fc-ab91-e7aeb5b5cb2d)

With:
![image](https://github.com/statiqdev/Statiq.Framework/assets/1020407/218a9f28-4922-4c9a-8598-faf7cf1fa3a1)

Does that satisfy your use case? If so I'll close out this issue and add some content to the docs about how to configure Markdig extensions that don't have a default constructor.

**Comment by kentcb** [comment] 2023-05-17 01:54
Thanks @daveaglick. Yes, I specifically wanted it for smart quotes, but it certainly looks like it's working based on your screenshots.

**Comment by daveaglick** [comment] 2023-05-17 16:29
Great, I'll go ahead and close this since there's already a way to add explicit Markdig extension instances, albeit undocumented. As far as documentation, I also went ahead and added a section to the documentation about how to do this too, and explained it might be needed if you see this error.

**Closed by daveaglick** 2023-05-17 16:29 UTC
Labels: Discussion/Question
